# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{subduino}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2011-08-29}
  s.description = %q{Interface, compile, upload... Play with arduino on ruby!}
  s.email = %q{x@nofxx.com}
  s.executables = ["subduino", "subduino-cli"]
  s.extensions = ["ext/subduino/extconf.rb"]
  s.files = [
    ".document",
    "Rakefile",
    "Readme.textile",
    "VERSION",
    "bin/subduino",
    "bin/subduino-cli",
    "duino/.gitignore",
    "duino/Makefile",
    "duino/duino.pde",
    "duino/duino.rb",
    "duino/methods.pde",
    "examples/duin",
    "ext/subduino/Makefile",
    "ext/subduino/cubduino.c",
    "ext/subduino/cubduino.h",
    "ext/subduino/cubduino.o",
    "ext/subduino/cubduino.so",
    "ext/subduino/extconf.rb",
    "lib/subduino.rb",
    "lib/subduino/ard_io.rb",
    "lib/subduino/ard_ps.rb",
    "lib/subduino/arduino.rb",
    "lib/subduino/os.rb",
    "lib/subduino/parse.rb",
    "lib/subduino/parse/bool.rb",
    "lib/subduino/parse/energy.rb",
    "lib/subduino/parse/flow.rb",
    "lib/subduino/parse/lux.rb",
    "lib/subduino/parse/presence.rb",
    "lib/subduino/parse/pressure.rb",
    "lib/subduino/parse/temp.rb",
    "lib/subduino/scaffold/Makefile",
    "lib/subduino/scaffold/Makefile2",
    "lib/subduino/scaffold/generator.rb",
    "lib/subduino/scaffold/scaffold.pde",
    "lib/subduino/scaffold/scaffold.rb",
    "lib/subduino/store.rb",
    "node/arduinode.js",
    "node/server.js",
    "node/vendor/faye.js",
    "spec/spec_helper.rb",
    "spec/subduino/ard_io_spec.rb",
    "spec/subduino/cubduino_spec.rb",
    "spec/subduino/parse_spec.rb",
    "spec/subduino/store_spec.rb",
    "spec/subduino_spec.rb",
    "subduino.gemspec"
  ]
  s.homepage = %q{http://github.com/nofxx/subduino}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Arduino Ruby Helpers}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<eventmachine>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<eventmachine>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

