# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{subduino}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2010-08-19}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{x@nofxx.com}
  s.executables = ["subduino-cli", "subduino"]
  s.files = [
    ".document",
     ".gitignore",
     "Rakefile",
     "Readme.textile",
     "Rub.h",
     "VERSION",
     "bin/subduino",
     "control.pde",
     "duino/Rakefile",
     "duino/Readme.textile",
     "duino/VERSION",
     "duino/lib/app.rb",
     "duino/lib/duino.rb",
     "duino/lib/environment.rb",
     "duino/lib/messenger.rb",
     "duino/public/app.css",
     "duino/public/app.js",
     "duino/public/icons/big_icon.png",
     "duino/public/icons/bookmark.png",
     "duino/public/icons/cpus.png",
     "duino/public/icons/databases.png",
     "duino/public/icons/gear.png",
     "duino/public/icons/groups.png",
     "duino/public/icons/info.png",
     "duino/public/icons/key.png",
     "duino/public/icons/mem.png",
     "duino/public/icons/monitor.png",
     "duino/public/icons/restart.png",
     "duino/public/icons/ruby.png",
     "duino/public/icons/server.png",
     "duino/public/icons/start.png",
     "duino/public/icons/stop.png",
     "duino/public/icons/terminal.png",
     "duino/public/icons/unmonitor.png",
     "duino/public/icons/unmonitored.png",
     "duino/public/icons/unmonitored_old.png",
     "duino/public/icons/up.png",
     "duino/public/icons/warn.png",
     "duino/public/icons/wrench.png",
     "duino/public/iui/backButton.png",
     "duino/public/iui/blueButton.png",
     "duino/public/iui/cancel.png",
     "duino/public/iui/grayButton.png",
     "duino/public/iui/greenButton.png",
     "duino/public/iui/iui-logo-touch-icon.png",
     "duino/public/iui/iui.css",
     "duino/public/iui/iui.js",
     "duino/public/iui/iuix.css",
     "duino/public/iui/iuix.js",
     "duino/public/iui/listArrow.png",
     "duino/public/iui/listArrowSel.png",
     "duino/public/iui/listGroup.png",
     "duino/public/iui/loading.gif",
     "duino/public/iui/pinstripes.png",
     "duino/public/iui/redButton.png",
     "duino/public/iui/selection.png",
     "duino/public/iui/thumb.png",
     "duino/public/iui/toggle.png",
     "duino/public/iui/toggleOn.png",
     "duino/public/iui/toolButton.png",
     "duino/public/iui/toolbar.png",
     "duino/public/iui/whiteButton.png",
     "duino/public/iui/yellowButton.png",
     "duino/public/right.js",
     "duino/spec/duino_spec.rb",
     "duino/spec/spec_helper.rb",
     "duino/views/command.haml",
     "duino/views/icon.haml",
     "duino/views/index.haml",
     "duino/views/switch.haml",
     "duino/views/top.haml",
     "lib/subduino.rb",
     "lib/subduino/arduino.rb",
     "lib/subduino/io.rb",
     "lib/subduino/ps.rb",
     "methods.pde",
     "spec/spec_helper.rb",
     "spec/subduino_spec.rb"
  ]
  s.homepage = %q{http://github.com/nofxx/subduino}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/subduino_spec.rb",
     "spec/spec_helper.rb",
     "spec/subduino/store_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

