---
log_interval: 60
inputs:
  i1:
    type: Temp
    name: Cafofo temp
  i2:
    type: Temp
    name: Out temp
  i3:
    type: Lux
    name: Cafofo light
  # i2:
  # i3:
  # i4:
  # i5:
outputs:
  d2:
    type: door
    name: Cafofo door
